# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f54d975b8cc40536cdb567dfc50d424de26e7220f152252e9a72bb1ad6cae5a22b1bf44189639a256b8b30c07465cf9b18f73ee3b38bd28d83d667e72c757628

test:
  secret_key_base: bdc18852804a0f9f517ac0374737522ebb820a677458b77803ed699904ed8de49a1bd53d9b7abd8983ffc912fce05cc70b129c78e758e74da455baf0dc5b3f58

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
